/**
 * Server-only entry point for @tanstack-use/ui.
 *
 * Import from "@tanstack-use/ui/server" inside "use server" files only.
 * Never import this from client components — it pulls in drizzle-orm and pg.
 */

import { QueryClient } from "@tanstack/react-query";
import { type AnyRoute, createRouter } from "@tanstack/react-router";
import type { App } from "@tanstack-use/core";
import { createAuthRoute } from "@tanstack-use/permissions";
import { createRoutes } from "./create-routes.js";

export type {
  CreateInput,
  DbRow,
  GetInput,
  ListInput,
  ModelServerFns,
  RemoveInput,
  UpdateInput,
} from "./server.functions.js";
export { serverFns } from "./server.functions.js";

/**
 * Builds the router from a file-based TanStack Router tree, adding:
 * - Model routes (list/detail/create) from `LayoutDef` definitions
 * - Auth API route for Better Auth integration
 *
 * The file-based `routeTree` (auto-generated by TanStack Router CLI from
 * files in `src/routes/`) is enhanced with programmatic model routes and
 * returned as a fully assembled router ready for use.
 *
 * @param routeTree - The file-based TanStack Router tree (routeTree.gen.ts)
 * @param app - The tanstack-use App with all models and auth config
 * @returns A fully configured TanStack Router instance
 */
export function getBaseRouter(routeTree: AnyRoute, app: App) {
  const queryClient = new QueryClient();

  // Access the route id — TanStack Router sets this as a plain property
  const routeId = (route: AnyRoute): string =>
    (route as unknown as { id: string }).id;

  // Find the _authenticated route so model routes are nested inside it
  const rootChildren = (routeTree.children as unknown as AnyRoute[]) ?? [];
  const authenticatedRoute = rootChildren.find(
    (child) => routeId(child) === "/_authenticated",
  ) ?? null;

  // Generate model routes
  const modelRoutes = authenticatedRoute
    ? createRoutes(app, authenticatedRoute)
    : [];

  // Create the auth route
  const authRoute = createAuthRoute(routeTree, {
    handler: async (req: Request) => {
      const auth = await import("@tanstack-use/core/server").then(
        (m) => m.appServer.auth,
      );
      return auth.handler(req);
    },
  });

  // Rebuild root children:
  // - filter out any stale /api/auth/$ (e.g. from hot-reload)
  // - replace _authenticated with a version that includes model routes
  const updatedRootChildren = rootChildren
    .filter((child) => routeId(child) !== "/api/auth/$")
    .map((child): AnyRoute => {
      if (routeId(child) !== "/_authenticated" || modelRoutes.length === 0) {
        return child;
      }
      // Nest model routes inside _authenticated, preserving any existing children
      const existingAuthChildren =
        (child.children as unknown as AnyRoute[]) ?? [];
      return child.addChildren([...existingAuthChildren, ...modelRoutes]);
    });

  const finalTree = routeTree.addChildren([...updatedRootChildren, authRoute]);

  const router = createRouter({
    routeTree: finalTree,
    context: { queryClient, session: null },
  });

  return router;
}
