/**
 * Server-only entry point for @tanstack-use/ui.
 *
 * Import from "@tanstack-use/ui/server" inside "use server" files only.
 * Never import this from client components — it pulls in drizzle-orm and pg.
 */

import { QueryClient } from "@tanstack/react-query";
import { type AnyRoute, createRouter } from "@tanstack/react-router";
import type { App } from "@tanstack-use/core";
import { createAuthRoute } from "@tanstack-use/permissions";
import { createRoutes } from "./create-routes.js";

export type {
  CreateInput,
  DbRow,
  GetInput,
  ListInput,
  ModelServerFns,
  RemoveInput,
  UpdateInput,
} from "./server.functions.js";
export { serverFns } from "./server.functions.js";

/**
 * Builds the router from a file-based TanStack Router tree, adding:
 * - Model routes (list/detail/create) from `LayoutDef` definitions
 * - Auth API route for Better Auth integration
 *
 * The file-based `routeTree` (auto-generated by TanStack Router CLI from
 * files in `src/routes/`) is enhanced with programmatic model routes and
 * returned as a fully assembled router ready for use.
 *
 * @param routeTree - The file-based TanStack Router tree (routeTree.gen.ts)
 * @param app - The tanstack-use App with all models and auth config
 * @returns A fully configured TanStack Router instance
 */
export function getBaseRouter(routeTree: AnyRoute, app: App) {
  const queryClient = new QueryClient();

  // Create the auth API route
  const authRoute = createAuthRoute(routeTree, {
    handler: async (req: Request) => {
      const auth = await import("@tanstack-use/core/server").then(
        (m) => m.appServer.auth,
      );
      return auth.handler(req);
    },
  });

  // Add only the auth route (don't modify existing file-based routes)
  // The route tree from routeTree.gen.ts has already been processed
  // and is finalized. We only add new programmatic routes here.
  routeTree.addChildren([authRoute]);

  const router = createRouter({
    routeTree,
    context: { queryClient, session: null },
  });

  return router;
}


